### PR TITLE
Add RSYNC module realm

### PR DESCRIPTION
**Pull request by jhart-r7**
I've followed CONTRIBUTING.md but even without this PR `bundle exec rake spec` fails for me so I cannot complete the testing required.

For https://github.com/rapid7/metasploit-framework/pull/6266

### CODE REVIEW

**Comment by wvu-r7** [comment]
Failing on ```master``` as well. Taking a look.

**Comment by jhart-r7** [comment]
Thanks @wvu-r7.  All of the tests fail horribly for me without this PR locally, and with this PR applied travis seems to have all of those same problems and more.

**Comment by wvu-r7** [comment]
We found the problem, and @sgonzalez-r7 is working on a fix. Related to https://github.com/rapid7/metasploit_data_models/pull/140.

**Comment by wvu-r7** [comment]
Complete fix here: https://github.com/rapid7/metasploit-model/pull/44.

**Comment by wvu-r7** [comment]
@jhart-r7: Would you mind rebasing or merging ```master```? Whichever you prefer. I think you rebase like some of us do.

**Comment by jhart-r7** [comment]
Sure.  Incoming.

**Pull request merged**
